runtime: custom
env: flex
skip_files:
- ^(.*/)?\.env$

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 10
network:
  instance_tag: quizlingo-instance
liveness_check:
  path: "/ping"
readiness_check:
  path: "/ping"
