runtime: custom
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 10
network:
  instance_tag: quizlingo-instance
  forwarded_ports:
    - 5000/tcp
liveness_check:
  path: "/ping"
readiness_check:
  path: "/ping"
